### ISSUE TITLE
Review content for Open Opportunity emails for state

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#135]
[Email Content.docx](https://github.com/openopps/OpenOppsTasks/files/2583170/Email.Content.docx)
Related Development Ticket 2653
Desired Due Date: 11/23/18

Debbie do you have time to review the emails that go out related to Creating/Approving Opportunties since that is our next big focus?    I want to discuss this with State during our meeting to see how they really would use these if at all.

1) Create Opportunity Saved as Draft

Dear Katrina Wagner,   Thank you for drafting an open opportunity.   Your draft can be found in your profile under   Drafts.   For your reference, here's a link to the opportunity: Testing Katrina Testing   Thanks,   The Open Opportunities Staging Team
--
2)  Opportunity Submitted Confirmation Email to Opportunity Creator
Hi Katrina Wagner,
Thanks for submitting Email Testing on Open Opportunities! We'll review your submission to make sure it has all the necessary information. We'll email you when it's approved or if we need more information.
Thanks,
The Open Opportunities Staging Team

3) Opportunity Submitted email to Administrator to tell them to approve:

Hi Katrina Wagner,   The message below was sent to a task creator because they created a new   task on Open Opportunities. Please review it and determine if it can be   approved or needs additional information and process appropriately.   Respectfully,   Open Opportunities Platform  
 ------------------------------------------   Hi Katrina Wagner,   Thanks for submitting Email   Testing on Open Opportunities! We'll review your submission to make sure   it has all the necessary information. We'll email you when it's approved or   if we need more information.   Thanks,   The Open Opportunities Staging Team
--
4) Opportunity approved and Open
Hi Katrina Wagner,
We approved your opportunity, Katrina Test 334, and it's now open and accepting applicants.
You'll get a notification each time someone signs up to participate in this opportunity.
What do you do now?
1.	Start reviewing and assigning participants.
2.	Cancel the opportunity if it's no longer needed.
Thanks,
The Open Opportunities Staging Team

Attaching the Word document which hasn't been updated in a while as an FYI

**Comment by dalenard21** [comment]
@kbwagner @Piglady64 

I've reviewed these and all of the ones in the word document.  There were a few disconnects between what's in the Airtable and what's in the word doc.  Here's some more specific feedback

1. "Create Opportunity - Draft" - in the Airtable we have this marked as an "Alert" and not an email.  I remember Min wanted to cut down on the number of emails we send and creating a 'draft' seemed like a good chance to just show an alert and not send an email.  Not sure if that ever got implemented in the current system, but if not, I'd like to revisit making it just an alert.

2. Opportunity submitted for review to Administrator - we don't have this email in the Airtable.  Also, I think it's strange to include the email to the creator as part of the email to the administrator.  I've attached the word doc with specific feedback.

3. I included more feedback/comments in the word doc, because it had more emails than what's listed in this git issue.

4. We should update the Airtable with anything that's missing and update the word doc with the correct content - let's review the Airtable content and make sure that's the version we want to use.

5. I'm interested to hear what State thinks of these emails. I can see these emails being useful for them,  but I wonder if they will want the language to be updated to use 'internship'.  Let's discuss in person.
[Open-opps-email-content-debbie-feedback_20181126.docx](https://github.com/openopps/OpenOppsTasks/files/2616789/Open-opps-email-content-debbie-feedback_20181126.docx)

**Comment by dalenard21** [comment]
@kbwagner here is an updated version of the Open Opps Email word doc including the new "Community Member Invite" email content.  I also updated the Airtable with the new email.

[Open-opps-email-content-debbie-feedback_20181212.docx](https://github.com/openopps/OpenOppsTasks/files/2672546/Open-opps-email-content-debbie-feedback_20181212.docx)

**Comment by dalenard21** [comment]
@kbwagner what's the next step needed for this?  Can we close?  Do we need to create a new issue to rewrite any of these for state?

**Comment by dalenard21** [comment]
@kbwagner @Piglady64 

Any updates on these emails for State?  Do you want me to 'rewrite' them to at least include 'internship opportunities', etc?

**Comment by Piglady64** [comment]
We are meeting with DoS on Wednesday 2/6 to go over the email content and then we will create a ticket development ticket

**Comment by Piglady64** [comment]
@dalenard21 please re-write them to include the "internship opportunity" language

**Comment by dalenard21** [comment]
@Piglady64 @kbwagner here's the create opportunity emails with comments/edits for DOS.  I have questions as 'comments' . I could see some of these being useful, but others I question.

[Open-opps-email-content-for-department-of-state_20190220.docx](https://github.com/openopps/OpenOppsTasks/files/2886169/Open-opps-email-content-for-department-of-state_20190220.docx)

**Comment by kbwagner** [comment]
@dalenard21 my comments are attached.  A lot of these can be removed.  not sure if we'll have time but we will try to review the touchpoints with them on Thursday 2/28 if we get through the apply process.
[Open-opps-email-content-for-department-of-state_20190220 kbw.docx](https://github.com/openopps/OpenOppsTasks/files/2906887/Open-opps-email-content-for-department-of-state_20190220.kbw.docx)

- wondering if we should eventually include the ATP emails in this document or create something similar for ATP so we can hand it over as part of the deployment process.

**Comment by kbwagner** [comment]
2/28/19 meeting with State agreed to these touchpoints: 
	Bureau internship coordinators:	
o	Draft internship opportunity created
o	Internship submitted for review
o	Internship approved
	Community manager:
o	Internship submitted
	Applicant:
o	Application received
o	Share internship opportunity 
o	Application withdrawn confirmation


Next step - update document with content and send to State for review
- Katrina to enter tickets in backlog
- Need to discuss the branding piece and figure out what we can do in open opps (which is another task ticket)

**Comment by dalenard21** [comment]
@kbwagner @Piglady64 

Here's another version of the Open Opps emails for DOS.  This version includes feedback from Katrina and Khadijah. It also includes the two new emails for the surveys.  I do have comments inserted throughout.

Please review and if it looks okay, send along to Khadijah for her review (or I can make edits before we do that).

[Open-opps-email-content-for-department-of-state_v3_20190304.docx](https://github.com/openopps/OpenOppsTasks/files/2927712/Open-opps-email-content-for-department-of-state_v3_20190304.docx)

**Comment by kbwagner** [comment]
@dalenard21 see my comments attached and let me know if you have any questions.
[Open-opps-email-content-for-department-of-state_v3_20190304 kw.docx](https://github.com/openopps/OpenOppsTasks/files/2937618/Open-opps-email-content-for-department-of-state_v3_20190304.kw.docx)

**Comment by dalenard21** [comment]
@Piglady64 @kbwagner here's the most up-to-date version of the Open Opps emails for State.  This is the same document  I sent to you via Slack last Friday (3/8)
[Open-opps-email-content-for-department-of-state_v4_20190308.docx](https://github.com/openopps/OpenOppsTasks/files/2956919/Open-opps-email-content-for-department-of-state_v4_20190308.docx)


@Piglady64 did you pass this along to Khadijah?  My email is working again, so I can do it if you haven't.

**Comment by dalenard21** [comment]
@Piglady64 @kbwagner 

Here are the updated Open Opps emails for DOS.  All of these emails will be coming from Open Opps.  But, maybe the 'survey' ones will come from DOS?  We can discuss.

@Piglady64 I updated the 'Thanks for your application" to reference Department of State and 'They" instead of "We".  Please let me know if you have any changes to that email or any others.

Thanks for your help.
[Open-opps-email-content-for-department-of-state-v5_20190321.docx](https://github.com/openopps/OpenOppsTasks/files/2993458/Open-opps-email-content-for-department-of-state-v5_20190321.docx)

**Comment by kbwagner** [comment]
6/4/19 - These tickets are complete.
