### ISSUE TITLE
Contractor changes

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#200]
USAJOBS will be moving the federal government email address to the contact information section of the profile. This will allow for contractors to more easily find this field.

To get into Open Opps as a contractor, you should not have answered you are a current federal employee but you must have a confirmed federal government email address.

Possible Content Changes:
- Review new account pages - any updates to reflect new position of email address?
- Review missing information pages - any updates to reflect new position of email address?

Do we need any specific context to say contractors who have a confirmed federal email address?

@dalenard21 @abudz19 - I listed out some pages below that will be affected by the change in location of the federal government email address in USAJOBS.
- I'm also wondering if we want to call out contractors?  For example on #1 below we show hiring paths of federal and student...but a contractor won't be either. Thoughts?

Pages where we should discuss whether something should be added:
1) Create your profile: https://opm.invisionapp.com/d/main#/console/15360465/358534511/preview - do we add a section for contractor?
2) https://opm.invisionapp.com/d/main#/console/15360465/358534509/preview - change location of email address
3) https://opm.invisionapp.com/d/main#/console/15360465/358534508/preview - change location of federal email address
4) https://opm.invisionapp.com/d/main#/console/15360465/358534507/preview - change location of federal email address - do we add an "if you're a contractor"

Help content:
1) https://usajobs.github.io/openopps-help/ (Benefits for federal employees and current students)Open Opportunities is only for federal employees, and students looking for internships.
2)section 2 on  https://usajobs.github.io/openopps-help/profile/ - edit location of federal government email address.  What about hiring path?

**Comment by dalenard21** [comment]
Hi @kbwagner , thanks for putting together this list.  I believe we're not moving the federal government email address field anymore, but rather adding an option for contractors to say they're a current federal contractor.

We'll still need to update several of the pages you listed above. I'll start working on some suggestions, but also need to see what @abudz19 mocks up for how that new 'option' will appear.

**Comment by dalenard21** [comment]
@kbwagner @abudz19 @tlorrison 

I've been thinking about how we want to capture the contractor status. I talked to Alex about it yesterday, but want to put it in here to open it up to everyone. 

I think the contractor question needs to be separate from the "Please select the statement that best reflects your federal employment status."  Here are a few reasons:

1. I COULD be a former federal employee who is now working as a contractor for the federal government. 
2. Even if I'm a federal contractor, I'm also "Not a federal employee" and therefore need to choose that option, in case I do want to do a job search and get relevant search results.
3. I don't think we want to allow for multiple selections in the current question about federal employment status, because if someone accidentally chooses "I'm a current fed and I'm a former fed", that will mess up the system/search results too (and their profile/hiring paths, etc.).

What do you think?

I've attached a suggestion of how this might work. 
[USAJOBS-profile-federal-service-with-contractor-option_20190726.docx](https://github.com/openopps/OpenOppsTasks/files/3436687/USAJOBS-profile-federal-service-with-contractor-option_20190726.docx)

**Comment by dalenard21** [comment]
@kbwagner @tlorrison @abudz19 

Additional feedback/suggestions. Per your questions Katrina, here are my thoughts:

1. Create your profile: https://opm.invisionapp.com/d/main#/console/15360465/358534511/preview - do we add a section for contractor?

Yes, I think we need to add a section for federal contractor.  We could something like this as a description:

"Current contractor who is working for the Federal Government and needs access to Open Opportunities."

2. https://opm.invisionapp.com/d/main#/console/15360465/358534509/preview - change location of email address

Based on the decision to not move the federal email address, I don't think we need to make any changes to this page.

3. https://opm.invisionapp.com/d/main#/console/15360465/358534508/preview - change location of federal email address

I think this page appears when a federal employee tries to sign in, and if so, then I don't think we need to update this page.

4. https://opm.invisionapp.com/d/main#/console/15360465/358534507/preview - change location of federal email address - do we add an "if you're a contractor"

We don't need to change the location of the email address, but I do think we need to add "If you're a contractor".  I added a word document with suggested content (the profile missing information doc)

5. New page?  If we add a section for "Federal contractor", then we'll need a new page if someone chooses that with instructions of what they need to do.  Similar to what we did for federal employee and student.  I added a word document with suggested content (the federal contractor steps doc)

6. Help content - I'm not sure we need to update https://usajobs.github.io/openopps-help/ to say contractors because the site really isn't for them to use.  We just need to give them access so they can post opportunities.  They can't apply to opportunities.  I want to think more about if we need to explain that some contractors can post opportunities. For https://usajobs.github.io/openopps-help/profile/ we probably should update it to talk about contractors selecting the right option in the federal service experience section.

[Open-opportunities-profile-missing-information_20190726.docx](https://github.com/openopps/OpenOppsTasks/files/3436919/Open-opportunities-profile-missing-information_20190726.docx)

[Open-opportunities-new-federal-contractor-steps_20190726.docx](https://github.com/openopps/OpenOppsTasks/files/3436940/Open-opportunities-new-federal-contractor-steps_20190726.docx)

**Comment by abudz19** [comment]
Here is the mockup I've done in Core, currently handed off to John Still for review: https://opm.invisionapp.com/share/VAT7A1JWC4F#/376270367_Federal_Service_-_Contractor_Reveal

Starting on the changes to the OO pages.

**Comment by abudz19** [comment]
Open Opps changes, starting here: https://opm.invisionapp.com/d/main#/console/15360465/358534511/preview

**Comment by dalenard21** [comment]
@abudz19 @kbwagner I think these screens look good.  Has there been any more discussion about the contractor changes while I was out?  And, do you know when these changes will go out?  I can start updating help center, but don't want to do it too early if these changes aren't going out.

**Comment by tlorrison** [comment]
Debbie,
The contractor changes will not be going out until 8.0, which will be in 6 weeks or so. There are still discussions happening about what is going to happen in the interim…there is a debate on whether or not the update will be toggled on/off on USAJOBS and what impacts that will have.

**Comment by dalenard21** [comment]
@tlorrison thanks for letting me know.  I won't do anything else with this ticket until closer to the release.  Speaking of, can we add a milestone for 8.0?  I think it would be helpful if we start assigning tickets to the releases/sprints, so we know what to work on first.

**Comment by kbwagner** [comment]
Design work for this ticket has been done.  Tickets are in development for release 8.0.

**Comment by dalenard21** [comment]
@kbwagner I have a draft of **How to create a profile** for open opportunities.  It includes adding in steps for a contractor. Can you please review to make sure it makes sense?

[Open-opportunities-help-how-to-create-a-profile_20190909.docx](https://github.com/openopps/OpenOppsTasks/files/3592085/Open-opportunities-help-how-to-create-a-profile_20190909.docx)

**Comment by kbwagner** [comment]
@dalenard21 - only two comments/questions.  Do we want to say that only feds and contractors can create and that the font was off on the new section.  Thanks!

[Open-opportunities-help-how-to-create-a-profile_20190909.docx](https://github.com/openopps/OpenOppsTasks/files/3595997/Open-opportunities-help-how-to-create-a-profile_20190909.docx)

**Comment by kbwagner** [comment]
@dalenard21 do we need to add contractors to the https://usajobs.github.io/openopps-help/

Benefits for federal employees and current students
Open Opportunities is only for federal employees, and students looking for internships. The program offers a wide variety of real world projects to work on.

**Comment by kbwagner** [comment]
@dalenard21 contractor changes for Open Opps will go out Monday 10/7.  do you want to chat more about any possible help center updates related to this?

**Comment by dalenard21** [comment]
@kbwagner I made some updates for the contractor changes. I decided to add some info on the "create opportunity" page. Here are the pages I updated:

https://federalist-proxy.app.cloud.gov/site/usajobs/openopps-help/opportunity/
https://federalist-proxy.app.cloud.gov/site/usajobs/openopps-help/profile/

Let's see if we get more questions about contractors--we can always add an FAQ about contractors.

**Comment by kbwagner** [comment]
@dalenard21 I reviewed and they look good.

What about this page: https://usajobs.github.io/openopps-help/ (Benefits for federal employees and current students)Open Opportunities is only for federal employees, and students looking for internships.

Is that the one you were talking about you wanted to udpate?

**Comment by kbwagner** [comment]
10/21/19 - Verified this is now live in production.
Closing.
Thanks!
