### ISSUE TITLE
Update to the internship applicant status 

### ISSUE THREAD

**Issue by kbwagner** [openopps/OpenOppsTasks#205]
We have added a new status for the internship applicant process that should be updated here: https://usajobs.github.io/openopps-help/opportunity/application-status/

Added: "Not submitted"
Application was not completed and submitted prior to the deadline and therefore was not sent forward

This change will hopefully go out with release 8.0 which is expected to go out the week of 10/7/19

Thanks!

**Comment by dalenard21** [comment]
Hi @kbwagner 

We have a status of 'In progress' for applications that are being worked on, but haven't been submitted yet.  So, will the "Not Submitted" status automatically show for any of these 'in progress' applications after the application period closes?  

Can a student submit an application after the deadline?  If not, then I don't think we want to describe it as "not sent forward", because the student just never sent it.  Does that make sense?

**Comment by kbwagner** [comment]
Yes, In progress shows for applications that are being worked on but haven't been submitted.  When the apply cycle ends and the student never hit submit, those in progress then change to Not submitted automatically.

Students can't submit after the deadline.  All internships will be pulled down.  Yep...you can ignore my verbiage was just trying to give you the details. @dalenard21

**Comment by dalenard21** [comment]
@kbwagner how does this sound?

**Not submitted**
You didn’t complete and submit the application before the deadline.

**Comment by kbwagner** [comment]
Sounds good @dalenard21 thanks!

**Comment by dalenard21** [comment]
@kbwagner I updated the page and it's in the 'test' federalist site here:
https://federalist-proxy.app.cloud.gov/site/usajobs/openopps-help/opportunity/application-status/

We just need to have Brice push it out when the release goes out.

**Comment by kbwagner** [comment]
@bmcorum for Monday release

**Comment by kbwagner** [comment]
This has been pushed out successfully to production.
