### ISSUE TITLE
State: Search page

### ISSUE THREAD

**Issue by mchung07** [openopps/OpenOppsTasks#97]
Create screens for Students internship search page

**Comment by humancompanion** [comment]
Review with Min today at 10am.

**Comment by humancompanion** [comment]
Min is revising this one today and next week. Target date 10/3.

**Comment by mchung07** [comment]
- [ ] General search page for Students
- [ ] Program specific search page (coming directly from unpaid internship site)
- [ ] Community admin's view

**Comment by humancompanion** [comment]
@abudz19 to find out from Tracy and Katrina when we will review with State.

**Comment by abudz19** [comment]
@humancompanion Per Katrina, Tracy has been checking with State, meeting not likely to happen this week. We will both be included on the invite when it goes out.

**Comment by abudz19** [comment]
@kbwagner can this be closed?

**Comment by kbwagner** [comment]
@abudz19 we will review on 11/15/18  with State 11-12:30

**Comment by kbwagner** [comment]
@humancompanion yes I looked through these today to see what we could close and didn't close it because of Min's note about the Community Admin View.  I'm not sure if their view is any different??  
- Also, there were some questions about whether Create Opportunity would ever show up.  My thought is if you're a community manager for a student community and are logged in then yes the Create Button can show up on the search page (Min has two search mocks one with and one without the create).  If you have any thoughts on that feel free to weigh in.  
- If we aren't doing a community admin view of search then I think we can close this.  If anything I would think it would be like the current admin where they just see different status filters.

**Comment by kbwagner** [comment]
Reviewed with State Dept 12/12 and the few changes are noted in Invision for Alex to update.  
- This can be closed.
